name         'camptocamp-mcollective'
version      '0.1.0'
dependency   'camptocamp/ruby', '0.0.1'
dependency   'puppetlabs/stdlib', '0.0.1'
dependency   'ripienaar/concat', '0.0.1'
source       'https://github.com/camptocamp/puppet-mcollective'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp MCollective Module'
description  'MCollective Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-mcollective'
